server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      routes:
        - id: person
          uri: lb://APP-PERSON
          predicates:
            - Path=/person/**
        - id: procedure
          uri: lb://APP-PROCEDURE
          predicates:
            - Path=/procedure/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
