server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        - id: person
          uri: http://localhost:8081
          predicates:
            - Path=/api/person/**
        - id: account
          uri: http://localhost:8082
          predicates:
            - Path=/api/account/**
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
