server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      routes:
        - id: person
          uri: lb://MSVC-PERSON
          predicates:
            - Path=/person/**
        - id: procedure
          uri: lb://MSVC-PROCEDURE
          predicates:
            - Path=/procedure/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
