server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        - id: person
          uri: lb://MSVC-PERSON
          predicates:
            - Path=/api/person/**
        - id: account
          uri: lb://MSVC-ACCOUNT
          predicates:
            - Path=/api/account/**
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/